#! /bin/sh

xsetroot -cursor_name left_ptr &
xset r rate 230 30 &
sxhkd &
nitrogen --restore &
picom --experimental-backend &
$HOME/.config/polybar/launch.sh &
nm-applet --indicator &
blueberry-tray &
#xidlehook --not-when-audio --not-when-fullscreen --timer 300 'systemctl suspend' '' &
#wmname LG3D &
clipmenud &
touchegg &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width         1
bspc config window_gap		 20

bspc config focused_border_color  "#BBA6E6"
bspc config normal_border_color   "#111111"
bspc config active_border_color   "#230B52"
bspc config presel_feedback_color "#4c566a"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a jetbrains-studio state=floating border=off follow=on
bspc rule -a anbox state=floating border=off follow=on
bspc rule -a CoreShot state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Dragon-drag-and-drop state=floating sticky=on focus=on
bspc rule -a Screenkey manage=off
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a kitty state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a scrcpy state=floating
